apiVersion: argoproj.io/v1alpha1 # Changed from apps/v1
kind: Rollout
metadata:
  name: todo-test-rollout
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  selector:
    matchLabels:
      app: todo-test
  template:
    metadata:
      labels:
        app: todo-test
    spec:
      containers:
        - name: todo-test
          image: unspecialfx/todo_test:blue 
          ports:
            - containerPort: 3000