apiVersion: v1
kind: Service
metadata:
  name: todo-test-service
spec:
  selector:
    app: todo-test
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 3000
      nodePort: 31000
  type: LoadBalancer 